version: '3'
services:
  php:
    container_name: app
    build: docker/app
    volumes:
      - .:/var/www
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8905:80
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - php
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: graphQL
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/etc/my.cnf:/etc/my.cnf
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/etc:/docker-entrypoint-initdb.d
    ports:
      - 4309:3306


  phpmyadmin:
    image: phpmyadmin
    container_name: qlAdmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 1011:80
    volumes:
      - /sessions